version: '3'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb_go_pos
    ports:
      - 3300:3306
    # [public]:[local]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pos